
branches:
  - name: "main"

repository:
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_squash_merge: true
  archived: false
  default_branch: "main"
  delete_branch_on_merge: true
  description: "An API Client for ConvertKit"
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  has_downloads: true
  has_issues: true
  has_pages: false
  has_projects: false
  has_wiki: false
  name: "convertkit-client"
  private: false
  topics: "email, mailing-list, convertkit, php, psr-18, psr-17"
