name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
      - 'renovate/**'
    tags:

jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x
  coverage:
    name: PHPUnit Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@2.26.0
        with:
          php-version: 8.1
          extensions: pcov
          coverage: pcov
          ini-values: pcov.enabled=1
      - uses: "ramsey/composer-install@2.2.0"
        with:
          dependency-versions: "highest"
      - run: php ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - uses: codecov/codecov-action@v4-beta
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false

  composer-require-checker:
    name: "Check for missing dependencies"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: shivammathur/setup-php@2.26.0
        with:
          php-version: 8.1

      - uses: "ramsey/composer-install@2.2.0"
        with:
          dependency-versions: "highest"

      - name: "Set global composer bin-dir"
        run: composer global config bin-dir /usr/local/bin

      - name: "Install require checker"
        run: composer global require -W maglnet/composer-require-checker

      - name: "Check"
        run: /usr/local/bin/composer-require-checker check
